version: '3.8'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /Users/abpyguru/Desktop/github/builds/adrianbx/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Users/abpyguru/Desktop/github/builds/adrianbx
    ports:
      - 8000:5432
    depends_on:
      - db

volumes:
  postgres_data: